# Generated by Django 2.1.7 on 2019-02-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('mag', models.DecimalField(decimal_places=10, max_digits=20)),
                ('depth', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
