# Generated by Django 2.1.7 on 2019-02-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingvapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quake',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
