# Generated by Django 2.1.7 on 2019-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingvapi', '0002_quake_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quake',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
